import Map from './components/Map'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'

const robot = Roboto({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-robot',
})

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
